import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { bundleMDX } from "mdx-bundler";
import { getMDXComponent } from "mdx-bundler/client";
import { useMemo } from "react";
import { getSortedPostsData } from "lib/utils";
import Link from "next/link";

const Home: NextPage = ({ posts }: any) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<ul>
					{posts.map((post: any) => (
						<li key={post.slug}>
							<Link href={`/blog/${post.slug}`}>{post.slug}</Link>
						</li>
					))}
				</ul>
			</main>
		</div>
	);
};

export default Home;

export async function getStaticProps() {
	const posts = getSortedPostsData();

	return {
		props: {
			posts,
		},
	};
}
